[package]
name = "concrat"
version = "1.0.0"
authors = ["Jaemin Hong <hjm0901@gmail.com>"]
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
rustfix = "0.6.0"
xml-rs = "0.8.4"
spin = "0.9.2"
clap = "2.34.0"
serde = "1.0.140"
serde_json = "1.0.82"
etrace = "1.1.1"

[package.metadata.rust-analyzer]
rustc_private = true
